# Generated by Django 5.0.4 on 2024-04-30 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=50)),
                ('CompanyEmail', models.CharField(max_length=50)),
                ('CompanyMobile', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Applies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PosName', models.CharField(max_length=50)),
                ('CompanyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobseeker')),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PosName', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('CompanyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
