# Generated by Django 5.0.4 on 2024-04-30 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_applies_apply_rename_positions_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='CompanyName',
        ),
        migrations.AlterField(
            model_name='apply',
            name='PosName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
    ]
