# Generated by Django 4.2.11 on 2024-04-30 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_position_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='User_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RegisteredUser',
        ),
    ]
