# Generated by Django 5.0.4 on 2024-04-30 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_apply_companyname_alter_apply_posname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='PosName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.position'),
        ),
    ]
