# Generated by Django 5.0.4 on 2024-04-30 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_apply_posname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobSeeker',
            new_name='RegisteredUser',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='PosName',
            new_name='Pos_Name',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='Name',
            new_name='User_Name',
        ),
    ]
